### PR TITLE
Implemented the typed-protocols Marlowe Sync client

### PR DESCRIPTION
**Pull request by dino-iog**
- Made new data and GADT definitions
- Implemented the Client hoist functions
- Implemented the Client peer functions
- Changed blockHeader* to header* for consistency

### CODE REVIEW

**Comment by jhbertra** [comment]
Don't forget to `updateMaterialized`

**Comment by dino-iog** [comment]
@jhbertra This has been squashed and rebased against your branch

**Comment by dino-iog** [comment]
Wait, what do I need to do with `updateMaterialized`?

**Comment by jhbertra** [comment]
Because you added a new module to the cabal package, the materialized files need updating

**Comment by dino-iog** [comment]
So, run `updateMaterialzed` and then commit changes to the nix files? It's taking a while of course, ok if I get lunch and finish after?

**Comment by jhbertra** [comment]
Yeah, exactly. Should take a minute or so to run

**Comment by dino-iog** [comment]
Forgot `updateMaterialized`, canceling this PR and will do a new one.

**Comment by jhbertra** [comment]
Why a new PR? Could just reopen this one and push the new commit

**Comment by jhbertra** [comment]
Anyway, the changes look great! If you want, you could also take a go at rewriting `runShowCommand` in `marlowe-runtime/marlowe-history-cli/Main.hs` to use the `MarloweSyncClient` instead of the raw `Peer` (which it currently uses). Something like this:

```hs
-- before
(result, _) <- runPeerWithDriver driver peerInit (startDState driver)
...

-- after
(result, _) <- runPeerWithDriver driver (marloweSyncClientPeer client) (startDState driver)
...
where
  client = MarloweSyncClient $ pure $ clientInit
  clientInit = ...
```

**Pull request closed without merging**
