### PR TITLE
Report warnings during auto contract execution

### PR DESCRIPTION
**Pull request by edsko**
This provides a simple PR that addresses #174. I have not added tests that verify the warnings.

### CODE REVIEW

**Review by yveshauser — COMMENTED** [review]
Thanks! Logging the warnings for sure makes sense

**Review by yveshauser — CHANGES_REQUESTED** [review]
`getAction` only tries to detect what the next action for the auto execution should be - the warnings should rather be logged after `computeTransaction`

**Comment by edsko** [comment]
> getAction only tries to detect what the next action for the auto execution should be - the warnings should rather be logged after computeTransaction

I don't fully understand. `getAction` is a pure function, it cannot do any logging, it merely computes what warnings there are alongside the action. The logging is done in `autoExecuteContract`, where there is other logging too. Not sure what you'd like to change, exactly?

**Comment by yveshauser** [comment]
> > getAction only tries to detect what the next action for the auto execution should be - the warnings should rather be logged after computeTransaction
> 
> I don't fully understand. `getAction` is a pure function, it cannot do any logging, it merely computes what warnings there are alongside the action. The logging is done in `autoExecuteContract`, where there is other logging too. Not sure what you'd like to change, exactly?

The warnings are available after the call to `computeTransaction` in the `mkStep` function. The `TransactionOutput` has a field `txOutWarnings` that contains the warnings that should be logged. `getAction` only tries to determine the possible next actions but does not trigger any payments.

**Comment by edsko** [comment]
Yes, but prior to this PR, any warnings encountered by `getAction` will be irrevocably lost (the `warnings` field of `ContractQueiest` was ignored). There can indeed be _additional_ warnings, depending on the action that is computed by `getAction`, but any warnings arising from computing what action that should be (and hence also independent of that action, because they arise primarily from the actions _before_ the action returned by `getAction` to be executed. The warnings that are returned as part of the output by `computeTransaction` are a different set.

For example, if a contract has two transfers, but the contract does not have sufficient  funds for the first transfer, prior to this PR, that first transfer is simply skipped over with no logging anywhere, and `computeTransaction` will not even get to see it.

But perhaps I am still misunderstanding you?

**Comment by yveshauser** [comment]
> Yes, but prior to this PR, any warnings encountered by `getAction` will be irrevocably lost (the `warnings` field of `ContractQueiest` was ignored). There can indeed be _additional_ warnings, depending on the action that is computed by `getAction`, but any warnings arising from computing what action that should be (and hence also independent of that action, because they arise primarily from the actions _before_ the action returned by `getAction` to be executed). The warnings that are returned as part of the output by `computeTransaction` are a different set.
> 
> For example, if a contract has two transfers, but the contract does not have sufficient funds for the first transfer, prior to this PR, that first transfer is simply skipped over with no logging anywhere, and `computeTransaction` will not even get to see it.
> 
> But perhaps I am still misunderstanding you?

Yes, the logging of the warnings is missing. In order to add it, I would propose to put it as follows:
```
diff --git a/marlowe/src/Language/Marlowe/Client.hs b/marlowe/src/Language/Marlowe/Client.hs
index 307b5a10b..3c4592177 100644
--- a/marlowe/src/Language/Marlowe/Client.hs
+++ b/marlowe/src/Language/Marlowe/Client.hs
@@ -1259,7 +1259,8 @@ mkStep MarloweParams{..} typedValidator timeInterval@(minTime, maxTime) clientIn
                 txInputs = inputs }

         case computeTransaction txInput marloweState marloweContract of
-            TransactionOutput {txOutPayments, txOutState, txOutContract} -> do
+            TransactionOutput {txOutWarnings, txOutPayments, txOutState, txOutContract} -> do
+                forM_ txOutWarnings $ \w -> logWarn $ "Warning: " <> show w
                 let marloweData = MarloweData {
                         marloweContract = txOutContract,
                         marloweState = txOutState }
```
As in `computeTransaction` the inputs get applied and the contract is reduced until quiescent. Only here a contract gets actually reduced - `getAction` only tries to detect inputs for the auto-execution and does not reduce the contract. Do you agree, or am I missing something?

**Comment by edsko** [comment]
I agree that it would be useful to log those warnings _as well_, but those are _different_ warnings than the warnings logged by this PR. The _combination_ of what you're doing and what I'm proposing would probably make the most sense: this PR as it should logged warnings that arose during `getAction`, and then the code you're adding will log any warnings that arise from the execution of the action returned by `getAction`.

**Comment by edsko** [comment]
Specifically, `reduceContractUntilQuiescent` can skip actions if they cannot be executed, for example due to lack of funds (see `reduceContractStep`, case for `Pay`). Such actions will result in warnings being returned from `reduceContractUntilQuiescent`; these are the warnings `getAction` bubbles up in my PR, along with the action that is to be executed _after_ the contract was reduced until quiescent.

**Comment by bwbush** [comment]
Merged as https://github.com/input-output-hk/marlowe-cardano/pull/207.

**Comment by edsko** [comment]
Thanks @bwbush ! :)

**Pull request closed without merging**
