### PR TITLE
SCP-4598 SCP-4604 SCP-4625 SCP-4626 Bug fixes to enable comprehensive Marlowe Runtime contract

### PR DESCRIPTION
**Pull request by bwbush**
- SCP-4598 creates a comprehensive contract for Marlowe Runtime testing
- SCP-4604 fixes coin selection when native assets are at the script address. Coin selection was not accounting for the value coming from the script address because that was not part of the wallet context. I added the marlowe context to the UTxO set so that coin selection could look up the value consumed from the script.
- SCP-4625 prevents coin selection from erroneously attempting to spend reference inputs.
- SCP-4626 fixes the incorrect redeemer that was used for payouts.

All together, these eliminate outstanding bugs that prevented [the comprehensive test contract](https://github.com/input-output-hk/marlowe-cardano/blob/SCP-4604/marlowe-runtime/examples/token-bid.ipynb) from being successfully executed with Marlowe Runtime.

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [ ] [Test report is updated](https://github.com/input-output-hk/marlowe-cardano/blob/main/marlowe/test/test-report.md) (if relevant)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Comment by bwbush** [comment]
Sorry, here are more details:
1. selectCoins builds a UTxO map from the wallet context only: https://github.com/input-output-hk/marlowe-cardano/blob/7b67fc7cc4646d3eb06c6ea1c7e853ddef56c3a8/marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Constraints.hs#L536.
2. The incoming value (from the constraints) is computed from the UTxO map: https://github.com/input-output-hk/marlowe-cardano/blob/7b67fc7cc4646d3eb06c6ea1c7e853ddef56c3a8/marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Constraints.hs#L562.
3. However, if a script UTxO is being spent, then it is providing value, too. This is ignored in the inputsFromBody computation because the filter (flip elem inputTxIns . fst) will not find those script inputs, since there weren't included in the UTxO set.
4. This problem also had existed in balanceTx, but it was fixed at https://github.com/input-output-hk/marlowe-cardano/blob/7b67fc7cc4646d3eb06c6ea1c7e853ddef56c3a8/marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Constraints.hs#L798-L800. That code is almost exactly what is needed in selectCoins, except of the TxOut context.
5. I consolidated the code embedded into balanceTx into a top-level function allUtxos that balanceTx could still use and that selectCoins would be able to use so that it has both the marlowe and wallet contexts.

**Comment by bwbush** [comment]
> However, if a script UTxO is being spent, then it is providing value, too.

We didn't see this error in cases where only lovelace was at the script address, since there is plenty of lovelace around for balancing. However, we do see the error if the script holds native tokens that the wallet doesn't, since then the script is the only source of the tokens required by the output constraints.

**Review by dino-iog — APPROVED** [review]

**Comment by dino-iog** [comment]
Ok with me to merge this.

**Comment by paluh** [comment]
Code changes looks ok - I reviewed them on Friday. I'm going test the notebooks on my branch later no.
Thanks a lot @bwbush!

**Pull request merged**
