### PR TITLE
SCP-4323 Skeleton for Marlowe Purescript Spec

### PR DESCRIPTION
**Pull request by hrajchert**
Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Review by palas — APPROVED** [review]
Looks good. One question: Is this meant to be the test suite or the adaptor to apply the test suite to marlowe purescript implementation?

If it is going to be the test suite, I would expect it to be a client rather than a server (to have the initiative). If it is going to be the adaptor for the "client test suite", then I don't understand why we need a generate random value end-point, I figure the entropy should be provided by the test suite.

Also one suggestion: it would be good to describe in the README how to run/use the tool

**Comment by hrajchert** [comment]
Sorry about this, before going into holiday I wrote the pertinent documentation as part of the PR instead of the Readme as this is still not very mature, but it seems that I forgot to save and the documentation was lost 🤦🏻 .

This is meant to be the skeleton of a client that the test suite will call to see if it is compliant. The generator is not implemented yet, but the main idea was to provide a way to keep the test suite blockchain agnostic and to allow each implementation to generate a valid address, token, etc.

The spec client reads from the `stdin` for request enclosed by delimitators. For the moment the beginning and ending delimitator is hardcoded to the triple backtick ` ``` <valid json request> ``` `, but eventually this could be configured via a command line parameter. The `json request` needs to have a `request`  key which is used to discriminate the particular request, and then some additional keys per request type. 

Currently the spec client has two commands

## test-roundtrip-serialization

This request test if a particular entity can be decoded and re-encoded.


#### A value
```
    {
    "request": "test-roundtrip-serialization", 
    "typeId": "Extended.Value",
    "json":
        { "add": 1
        , "and": 2
        }
    }
```

#### Another value

```
{
  "request": "test-roundtrip-serialization",
  "typeId": "Extended.Value",
  "json": {
    "multiply": {
      "add": "time_interval_start",
      "and": {
        "amount_of_token": { "currency_symbol": "ABC", "token_name": "abc" },
        "in_account": { "role_token": "party" }
      }
    },
    "times": {
      "value_of_choice": { "choice_name": "name", "choice_owner": { "role_token": "party" }}
    }
  }
}
```

#### A module 
```
{
  "request": "test-roundtrip-serialization",
  "typeId": "Extended.Module",
  "json": {
    "metadata": {
      "valueParameterInfo": [
        [
          "Amount of Ada",
          {
            "valueParameterFormat": {
              "contents": [0, "₳"],
              "tag": "DecimalFormat"
            },
            "valueParameterDescription": "Amount of Ada to be exchanged for dollars."
          }
        ],
        [
          "Amount of dollars",
          {
            "valueParameterFormat": {
              "contents": [0, "$"],
              "tag": "DecimalFormat"
            },
            "valueParameterDescription": "Amount of dollar tokens to be exchanged for Ada."
          }
        ]
      ],
      "timeParameterDescriptions": [
        ["Timeout for Ada deposit", "Deadline by which Ada must be deposited."],
        [
          "Timeout for dollar deposit",
          "Deadline by which dollar tokens must be deposited (must be after the deadline for Ada deposit)."
        ]
      ],
      "roleDescriptions": [
        ["Ada provider", "The party that provides the Ada."],
        ["Dollar provider", "The party that provides the dollar tokens."]
      ],
      "contractType": "Swap",
      "contractShortDescription": "Atomically exchange of Ada and dollar tokens.",
      "contractName": "Swap of Ada and dollar tokens",
      "contractLongDescription": "Waits until one party deposits Ada and the other party deposits dollar tokens. If both parties collaborate it carries the exchange atomically, otherwise parties are refunded.",
      "choiceInfo": []
    },
    "me_version": 1,
    "contract": {
      "when": [
        {
          "then": {
            "when": [
              {
                "then": {
                  "token": {
                    "token_name": "",
                    "currency_symbol": ""
                  },
                  "to": {
                    "party": {
                      "role_token": "Dollar provider"
                    }
                  },
                  "then": {
                    "token": {
                      "token_name": "dollar",
                      "currency_symbol": "85bb65"
                    },
                    "to": {
                      "party": {
                        "role_token": "Ada provider"
                      }
                    },
                    "then": "close",
                    "pay": {
                      "constant_param": "Amount of dollars"
                    },
                    "from_account": {
                      "role_token": "Dollar provider"
                    }
                  },
                  "pay": {
                    "times": {
                      "constant_param": "Amount of Ada"
                    },
                    "multiply": 1000000
                  },
                  "from_account": {
                    "role_token": "Ada provider"
                  }
                },
                "case": {
                  "party": {
                    "role_token": "Dollar provider"
                  },
                  "of_token": {
                    "token_name": "dollar",
                    "currency_symbol": "85bb65"
                  },
                  "into_account": {
                    "role_token": "Dollar provider"
                  },
                  "deposits": {
                    "constant_param": "Amount of dollars"
                  }
                }
              }
            ],
            "timeout_continuation": "close",
            "timeout": {
              "time_param": "Timeout for dollar deposit"
            }
          },
          "case": {
            "party": {
              "role_token": "Ada provider"
            },
            "of_token": {
              "token_name": "",
              "currency_symbol": ""
            },
            "into_account": {
              "role_token": "Ada provider"
            },
            "deposits": {
              "times": {
                "constant_param": "Amount of Ada"
              },
              "multiply": 1000000
            }
          }
        }
      ],
      "timeout_continuation": "close",
      "timeout": {
        "time_param": "Timeout for Ada deposit"
      }
    }
  }
}
```

## compute-transaction
This request prints the output of computing a transaction on a given contract and state

### Useless transaction
```
{
  "request": "compute-transaction",
  "state": {
    "accounts": [],
    "choices": [],
    "boundValues": [],
    "minTime": 1658509388985
  },
  "transactionInput": {
    "tx_interval": { "from": 1658509400000, "to": 1658509400100 },
    "tx_inputs": []
  },
  "coreContract": {
    "when": [
      {
        "then": {
          "when": [
            {
              "then": {
                "token": { "token_name": "", "currency_symbol": "" },
                "to": { "party": { "role_token": "Dollar provider" } },
                "then": {
                  "token": {
                    "token_name": "dollar",
                    "currency_symbol": "85bb65"
                  },
                  "to": { "party": { "role_token": "Ada provider" } },
                  "then": "close",
                  "pay": 20,
                  "from_account": { "role_token": "Dollar provider" }
                },
                "pay": { "times": 10, "multiply": 1000000 },
                "from_account": { "role_token": "Ada provider" }
              },
              "case": {
                "party": { "role_token": "Dollar provider" },
                "of_token": {
                  "token_name": "dollar",
                  "currency_symbol": "85bb65"
                },
                "into_account": { "role_token": "Dollar provider" },
                "deposits": 20
              }
            }
          ],
          "timeout_continuation": "close",
          "timeout": 1658509788985
        },
        "case": {
          "party": { "role_token": "Ada provider" },
          "of_token": { "token_name": "", "currency_symbol": "" },
          "into_account": { "role_token": "Ada provider" },
          "deposits": { "times": 10, "multiply": 1000000 }
        }
      }
    ],
    "timeout_continuation": "close",
    "timeout": 1658509488985
  }
}
```

### Transaction success
```
{
  "request": "compute-transaction",
  "state": {
    "accounts": [],
    "choices": [],
    "boundValues": [],
    "minTime": 1658509388985
  },
  "transactionInput": {
    "tx_interval": { "from": 1658509400000, "to": 1658509400100 },
    "tx_inputs": [
      {
        "input_from_party": { "role_token": "Ada provider" },
        "that_deposits": 10000000,
        "of_token": { "token_name": "", "currency_symbol": "" },
        "into_account": { "role_token": "Ada provider" }
      }
    ]
  },
  "coreContract": {
    "when": [
      {
        "then": {
          "when": [
            {
              "then": {
                "token": { "token_name": "", "currency_symbol": "" },
                "to": { "party": { "role_token": "Dollar provider" } },
                "then": {
                  "token": {
                    "token_name": "dollar",
                    "currency_symbol": "85bb65"
                  },
                  "to": { "party": { "role_token": "Ada provider" } },
                  "then": "close",
                  "pay": 20,
                  "from_account": { "role_token": "Dollar provider" }
                },
                "pay": { "times": 10, "multiply": 1000000 },
                "from_account": { "role_token": "Ada provider" }
              },
              "case": {
                "party": { "role_token": "Dollar provider" },
                "of_token": {
                  "token_name": "dollar",
                  "currency_symbol": "85bb65"
                },
                "into_account": { "role_token": "Dollar provider" },
                "deposits": 20
              }
            }
          ],
          "timeout_continuation": "close",
          "timeout": 1658509788985
        },
        "case": {
          "party": { "role_token": "Ada provider" },
          "of_token": { "token_name": "", "currency_symbol": "" },
          "into_account": { "role_token": "Ada provider" },
          "deposits": { "times": 10, "multiply": 1000000 }
        }
      }
    ],
    "timeout_continuation": "close",
    "timeout": 1658509488985
  }
}
```

**Comment by hrajchert** [comment]
To test, enter the directory, do a `spago install`, `spago build`, and then execute `node index.js`. Eventually we will add a nix-shell command

**Comment by palas** [comment]
> Sorry about this, before going into holiday I wrote the pertinent documentation as part of the PR instead of the Readme as this is still not very mature, but it seems that I forgot to save and the documentation was lost 🤦🏻 .
> 
> This is meant to be the skeleton of a client that the test suite will call to see if it is compliant. The generator is not implemented yet, but the main idea was to provide a way to keep the test suite blockchain agnostic and to allow each implementation to generate a valid address, token, etc.
> 
> The spec client reads from the `stdin` for request enclosed by delimitators. For the moment the beginning and ending delimitator is hardcoded to the triple backtick `` ``` <valid json request> ``` ``, but eventually this could be configured via a command line parameter. The `json request` needs to have a `request` key which is used to discriminate the particular request, and then some additional keys per request type.
> 
> Currently the spec client has two commands
> 
> ## test-roundtrip-serialization
> This request test if a particular entity can be decoded and re-encoded.
> 
> #### A value
> ```
>     {
>     "request": "test-roundtrip-serialization", 
>     "typeId": "Extended.Value",
>     "json":
>         { "add": 1
>         , "and": 2
>         }
>     }
> ```
> 
> #### Another value
> ```
> {
>   "request": "test-roundtrip-serialization",
>   "typeId": "Extended.Value",
>   "json": {
>     "multiply": {
>       "add": "time_interval_start",
>       "and": {
>         "amount_of_token": { "currency_symbol": "ABC", "token_name": "abc" },
>         "in_account": { "role_token": "party" }
>       }
>     },
>     "times": {
>       "value_of_choice": { "choice_name": "name", "choice_owner": { "role_token": "party" }}
>     }
>   }
> }
> ```
> 
> #### A module
> ```
> {
>   "request": "test-roundtrip-serialization",
>   "typeId": "Extended.Module",
>   "json": {
>     "metadata": {
>       "valueParameterInfo": [
>         [
>           "Amount of Ada",
>           {
>             "valueParameterFormat": {
>               "contents": [0, "₳"],
>               "tag": "DecimalFormat"
>             },
>             "valueParameterDescription": "Amount of Ada to be exchanged for dollars."
>           }
>         ],
>         [
>           "Amount of dollars",
>           {
>             "valueParameterFormat": {
>               "contents": [0, "$"],
>               "tag": "DecimalFormat"
>             },
>             "valueParameterDescription": "Amount of dollar tokens to be exchanged for Ada."
>           }
>         ]
>       ],
>       "timeParameterDescriptions": [
>         ["Timeout for Ada deposit", "Deadline by which Ada must be deposited."],
>         [
>           "Timeout for dollar deposit",
>           "Deadline by which dollar tokens must be deposited (must be after the deadline for Ada deposit)."
>         ]
>       ],
>       "roleDescriptions": [
>         ["Ada provider", "The party that provides the Ada."],
>         ["Dollar provider", "The party that provides the dollar tokens."]
>       ],
>       "contractType": "Swap",
>       "contractShortDescription": "Atomically exchange of Ada and dollar tokens.",
>       "contractName": "Swap of Ada and dollar tokens",
>       "contractLongDescription": "Waits until one party deposits Ada and the other party deposits dollar tokens. If both parties collaborate it carries the exchange atomically, otherwise parties are refunded.",
>       "choiceInfo": []
>     },
>     "me_version": 1,
>     "contract": {
>       "when": [
>         {
>           "then": {
>             "when": [
>               {
>                 "then": {
>                   "token": {
>                     "token_name": "",
>                     "currency_symbol": ""
>                   },
>                   "to": {
>                     "party": {
>                       "role_token": "Dollar provider"
>                     }
>                   },
>                   "then": {
>                     "token": {
>                       "token_name": "dollar",
>                       "currency_symbol": "85bb65"
>                     },
>                     "to": {
>                       "party": {
>                         "role_token": "Ada provider"
>                       }
>                     },
>                     "then": "close",
>                     "pay": {
>                       "constant_param": "Amount of dollars"
>                     },
>                     "from_account": {
>                       "role_token": "Dollar provider"
>                     }
>                   },
>                   "pay": {
>                     "times": {
>                       "constant_param": "Amount of Ada"
>                     },
>                     "multiply": 1000000
>                   },
>                   "from_account": {
>                     "role_token": "Ada provider"
>                   }
>                 },
>                 "case": {
>                   "party": {
>                     "role_token": "Dollar provider"
>                   },
>                   "of_token": {
>                     "token_name": "dollar",
>                     "currency_symbol": "85bb65"
>                   },
>                   "into_account": {
>                     "role_token": "Dollar provider"
>                   },
>                   "deposits": {
>                     "constant_param": "Amount of dollars"
>                   }
>                 }
>               }
>             ],
>             "timeout_continuation": "close",
>             "timeout": {
>               "time_param": "Timeout for dollar deposit"
>             }
>           },
>           "case": {
>             "party": {
>               "role_token": "Ada provider"
>             },
>             "of_token": {
>               "token_name": "",
>               "currency_symbol": ""
>             },
>             "into_account": {
>               "role_token": "Ada provider"
>             },
>             "deposits": {
>               "times": {
>                 "constant_param": "Amount of Ada"
>               },
>               "multiply": 1000000
>             }
>           }
>         }
>       ],
>       "timeout_continuation": "close",
>       "timeout": {
>         "time_param": "Timeout for Ada deposit"
>       }
>     }
>   }
> }
> ```
> 
> ## compute-transaction
> This request prints the output of computing a transaction on a given contract and state
> 
> ### Useless transaction
> ```
> {
>   "request": "compute-transaction",
>   "state": {
>     "accounts": [],
>     "choices": [],
>     "boundValues": [],
>     "minTime": 1658509388985
>   },
>   "transactionInput": {
>     "tx_interval": { "from": 1658509400000, "to": 1658509400100 },
>     "tx_inputs": []
>   },
>   "coreContract": {
>     "when": [
>       {
>         "then": {
>           "when": [
>             {
>               "then": {
>                 "token": { "token_name": "", "currency_symbol": "" },
>                 "to": { "party": { "role_token": "Dollar provider" } },
>                 "then": {
>                   "token": {
>                     "token_name": "dollar",
>                     "currency_symbol": "85bb65"
>                   },
>                   "to": { "party": { "role_token": "Ada provider" } },
>                   "then": "close",
>                   "pay": 20,
>                   "from_account": { "role_token": "Dollar provider" }
>                 },
>                 "pay": { "times": 10, "multiply": 1000000 },
>                 "from_account": { "role_token": "Ada provider" }
>               },
>               "case": {
>                 "party": { "role_token": "Dollar provider" },
>                 "of_token": {
>                   "token_name": "dollar",
>                   "currency_symbol": "85bb65"
>                 },
>                 "into_account": { "role_token": "Dollar provider" },
>                 "deposits": 20
>               }
>             }
>           ],
>           "timeout_continuation": "close",
>           "timeout": 1658509788985
>         },
>         "case": {
>           "party": { "role_token": "Ada provider" },
>           "of_token": { "token_name": "", "currency_symbol": "" },
>           "into_account": { "role_token": "Ada provider" },
>           "deposits": { "times": 10, "multiply": 1000000 }
>         }
>       }
>     ],
>     "timeout_continuation": "close",
>     "timeout": 1658509488985
>   }
> }
> ```
> 
> ### Transaction success
> ```
> {
>   "request": "compute-transaction",
>   "state": {
>     "accounts": [],
>     "choices": [],
>     "boundValues": [],
>     "minTime": 1658509388985
>   },
>   "transactionInput": {
>     "tx_interval": { "from": 1658509400000, "to": 1658509400100 },
>     "tx_inputs": [
>       {
>         "input_from_party": { "role_token": "Ada provider" },
>         "that_deposits": 10000000,
>         "of_token": { "token_name": "", "currency_symbol": "" },
>         "into_account": { "role_token": "Ada provider" }
>       }
>     ]
>   },
>   "coreContract": {
>     "when": [
>       {
>         "then": {
>           "when": [
>             {
>               "then": {
>                 "token": { "token_name": "", "currency_symbol": "" },
>                 "to": { "party": { "role_token": "Dollar provider" } },
>                 "then": {
>                   "token": {
>                     "token_name": "dollar",
>                     "currency_symbol": "85bb65"
>                   },
>                   "to": { "party": { "role_token": "Ada provider" } },
>                   "then": "close",
>                   "pay": 20,
>                   "from_account": { "role_token": "Dollar provider" }
>                 },
>                 "pay": { "times": 10, "multiply": 1000000 },
>                 "from_account": { "role_token": "Ada provider" }
>               },
>               "case": {
>                 "party": { "role_token": "Dollar provider" },
>                 "of_token": {
>                   "token_name": "dollar",
>                   "currency_symbol": "85bb65"
>                 },
>                 "into_account": { "role_token": "Dollar provider" },
>                 "deposits": 20
>               }
>             }
>           ],
>           "timeout_continuation": "close",
>           "timeout": 1658509788985
>         },
>         "case": {
>           "party": { "role_token": "Ada provider" },
>           "of_token": { "token_name": "", "currency_symbol": "" },
>           "into_account": { "role_token": "Ada provider" },
>           "deposits": { "times": 10, "multiply": 1000000 }
>         }
>       }
>     ],
>     "timeout_continuation": "close",
>     "timeout": 1658509488985
>   }
> }
> ```

I see, so we will only ask the client to generate random parties and things like that, right? Not generate a random `Value`, for example. Cause having the client provide the generators seems like a vulnerability, because they could just pass the tests by providing bad generators. For example, if all values generated are `Constant 0` or all contracts generated are `Close` then it is very easy to pass the benchmark.

Also, if the test suite calls the client, then it is not a client, it is a server :)

**Review by bwbush — APPROVED** [review]
Is there a way for me to test this? The read-me doesn't provide instructions.

**Comment by hrajchert** [comment]
Sorry, I forgot to also include `npm install`

**Comment by bwbush** [comment]
Yes, after including `npm install`, I was able to successfully send a request. Thanks!

**Comment by ladamesny** [comment]
Please reopen against purescript marlowe.

**Pull request closed without merging**
