### PR TITLE
PLT-6838 Optimise ChainSeek

### PR DESCRIPTION
**Pull request by jhbertra**
- [x] Adds a new `Scan` mode to chain seek protocol
- [x] Implementation for `marlowe-chain-indexer` rewritten to use `Scan` for bulk querying. 
- [x] Tested on `preprod`
  - Time to sync (against fully synced chain DB) on the order of 1 minute
- [x] Tested on `preview`
  - Time to sync (against fully synced chain DB) on the order of 5 minutes
- [ ] Tested on `mainnet`
  - Time to sync (against fully synced chain DB) __

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Formatting, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
        - Review required
        - [x] Substantial changes to code, test, or documentation
    - [x] Reviewer requested

### CODE REVIEW

**Comment by jhbertra** [comment]
# How to test

## Setup

- Fully synced runtime databases are required for each network to be tested
- Stop all runtime services (to be on the safe side, this is not a requirement for upgrading just for test integrity)
- Take a backup of the current `marlowe` schema for comparison later
- Wipe the `marlowe` schema (`delete from marlowe.block where true`)
- Start the runtime services built from the code from this branch

## Test 1: time to sync

- Time how long the indexer takes to reach the tip from genesis (it is ok to be a bit vague here, order of magnitude is more important than exact times)

## Test 2: verify contents

- Once synced, restore the previously backed up `marlowe` schema to a new schema, and compare its contents to the newly synced `marlowe` schema.

**Comment by bwbush** [comment]
> * Wipe the `marlowe` schema (`delete from marlowe.block where true`)

Recipe does not work. I'll drop the schema and assocatiate sqitch records, and test from there.

```console
ERROR:  update or delete on table "block" violates foreign key constraint "rollbackblock_toblock_fkey" on table "rollbackblock"
DETAIL:  Key (id)=(\x38c5ae7e259b20f06b7d04790b483c4bdcf98ab69bafbc60192a3f2a903a6ed9) is still referenced from table "rollbackblock".
```

**Comment by jhbertra** [comment]
Ah, you may first have to `delete from marlowe.rollbackblock where true`

**Comment by bwbush** [comment]
For `preview`, numerous blocks are missing from the new index, compared to the old version, yet both have reached the tip. This cascades into missing records for `applytx` and other tables.

```console
preview=# select count(*) from (select * from marlowe.block except select * from marlowesave.block) c;
 count 
-------
     0
(1 row)

preview=# select count(*) from (select * from marlowesave.block except select * from marlowe.block) c;
 count 
-------
 11951
(1 row)

preview=# select max(blockno) from marlowe.block;
   max   
---------
 1033673
(1 row)

preview=# select max(blockno) from marlowesave.block;
   max   
---------
 1033673
(1 row)
```

**Comment by jhbertra** [comment]
> 

Thanks, I'll see if I can reproduce locally!

**Review by bwbush — APPROVED** [review]

**Pull request merged**
