### PR TITLE
Wolfram Oracles Reference PR

### PR DESCRIPTION
**Pull request by dk14**
Hi, Marlowe Team!

This is a reference PR for future integrations between Wolfram Blockchain and Marlowe Oracles.

See also: https://github.com/dk14/marlowe-wolfram-starter-kit/

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] [Test report is updated](https://github.com/input-output-hk/marlowe-cardano/blob/main/marlowe/test/test-report.md) (if relevant)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
        - Review required
        - [x] Substantial changes to code, test, or documentation
        - [ ] Change made to Marlowe validator (@bwbush and @palas must be included as reviewers)
        - Review not required
        - [ ] Minor changes to non-critical code, documentation, nix derivations, configuration files, or scripts
        - [ ] Formatting, spelling, grammar, or reorganization
    - [x] Reviewer requested

### CODE REVIEW

**Comment by bwbush** [comment]
@dk14, thank you for drafting this pull request. Would you also please provide a link to the license agreement governing this data feed?

**Comment by dk14** [comment]
@bwbush Hi Brian, it's Matt (Dmytro Kondratiuk). Apologies for late reply.

I'm just a part-time consultant for Wolfram Blockchain, since I developed Marlowe ACTUS in the past.
How is Simon doing? :)

I should have a meeting with Wolfram Blockchian this week, so I'll ask around about licensing.

In reality, this PR is just for reference (not merging), since real wolfram Blockchain API is not ready yet.

As of this particular educational data feed, it's just WolphramAlpha|Mathematica, so here's the licensing: https://www.wolframalpha.com/termsofuse.

It requires AppId, so if you really want to add it to main branch - you'd need to either leave it as a parameter so users would be legally responsible, or register Marlowe Oracle as an app, and follow the agreement you sign during registration.

https://products.wolframalpha.com/simple-api/documentation

The actual Wolfram Blockchain that currently is in development might have different licensing though.

----

P.S. On unrelated note, but since I'm here:

I really prefer "passive" oracles to the "active" one implemented here. Alex nemish didn't implement "passive" at the time mainly because of lack of crypto-support for signature verification for a curve he needed - now plutus supports most curves, thus it should be strait-forward to implement.

So, ideally, it would be nice if you could add signature verification to cardano implementation of marlowe semantics.

It would only require:
- some extra meta information: "ChoiceId -> signature type x public_key x time-bound" map 
- Choice IO that would decode input containing `timestamp x value x signature` into `value
- Choice IO that would fail transaction if signature is wrong, similar to how role ownership is verified currently. 

It won't require changes in Marlowe semantics/proofs/Z3 since it's IO only, so the change is pretty light.

-----

Also, I didn't find any dockerizations of Marlowe Oracle, that I could use in Jupyter notebooks for instance.

-----
One more thing, Marlowe Playground could be used as widget for simulating Marlowe contracts from Javascript as I'm doing here (in a bit hacky way):

https://dk14.github.io/marlowe-wolfram-webdoc/
https://github.com/dk14/marlowe-wolfram-webdoc

Basically I used a web-archived snapshot of Marlowe PG as a widget (educational purposes only). I also use it to sample a payoff curve in order to generate a Bitcoin DLC contract, so in a way it demonstrates that Marlowe can be used as a language for BTC contracts too, since all BTC contract needs is a dictionary from oracle's observation to payout distribution (there are links to BTC-DLC paper in webdoc). Real prod version would be different, especially for stateful contracts (with multiple choices), but still possible even without running into dimensionality curse.

-----------

Unfortunately, in my webdoc I had to interact with playground in select-click style: https://github.com/dk14/marlowe-wolfram-webdoc/blob/5b0504b1b2dafcb72c8eb966f055a036c6e001b3/app.ts#L72. 

It would be nice if Marlowe Playground was exposed as a typescript library (npm package) additionally, where:

- you can specify contract source string and render a widget as a DOM-element (shadow root for example).
- you can progress simulation programmatically (in a widget and headless) and read contents of transaction log in a structure way.

While current Purescript tests of Playground allow to do those things in theory, it would be nice to have an actual user-friendly Typescript API exposed and packaged.

Thank you :)

**Comment by dk14** [comment]
I can describe Marlowe related ideas abova in more detail if you drop me an invite at dmkndr@gmail.com.

**Comment by palas** [comment]
hey @dk14 :wave:,

Thanks for the PR. Sorry it is taking us a bit to process it, but we will get to it.

Cheers!

**Comment by dk14** [comment]
@palas Sure, take ur time. I don't consult them anymore, but can still clarify the things I wrote above.

P.S. Don't forget to play my game "Energy Paddle" on AppStore

**Comment by bwbush** [comment]
The `marlowe-oracle` executable now supports the addition of [custom feeds](https://github.com/input-output-hk/marlowe-cardano/blob/main/marlowe-apps/Oracle.md#custom-external-feeds), so direct support for this data feed is not needed. Thank you.

**Comment by dk14** [comment]
@bwbush great! Have u considered adding "common sense" oracle support to Marlowe, since holiness of marlowe interpreter and "most definance does it" doesn't justify absence of native signature verification functionality in Marlowe?

P.S. Maybe I should've chosen better word than reference but the PR never meant to be merged, so u could've closed it from the start. It was rather a way to publish an example.

**Pull request closed without merging**
