### PR TITLE
SCP-2622: Document deployment details.

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by shlevy** [comment]
@palas Let me know if the docs here and on `plutus-ops` are sufficient or if you want me to do a quick walkthrough for the team.

**Review by palas — APPROVED** [review]
Yes this is clear. I would like to run through handling personal testing environments like we had before with `https://pablo.*.iohkdev.io/` and so on

**Comment by shlevy** [comment]
@palas Did you see the documentation for this in plutus-ops? https://github.com/input-output-hk/plutus-ops#ad-hoc-environments

If you like we can set up time with the team and work through creating one of these together.

**Comment by hrajchert** [comment]
Please, let's do that!

**Pull request merged**
