### PR TITLE
WIP: attempt flake fixes

### PR DESCRIPTION
**Pull request by jonringer**
Testing theory about flake issues.

### CODE REVIEW

**Comment by jhbertra** [comment]
Based on the status checks, it seems like this doesn't fix the issue

**Comment by jonringer** [comment]
> Based on the status checks, it seems like this doesn't fix the issue

still WIP :)

**Comment by jonringer** [comment]
IFD really complicates trying to fix evaluation issues, as now evaluation and building has been blurred.

**Comment by jonringer** [comment]
getting

```
$ nix-env -qaP -f ./release.nix
error: cannot import '/nix/store/g5i4jgq6vl1z0w95g0npxzj7x4048rnr-source/nix/lib/purescript.nix', since path '/nix/store/wf4sdy9rjcvpnrwrsl8g7n1rjbby1b0a-source.drv' is not valid
```

issues when evaluating with darwin. Someone with intel darwin hardware will need to research that issue.

**Comment by jhbertra** [comment]
I have an iMac with Nix installed, I can look into it tomorrow

**Comment by jonringer** [comment]
Next plan would be to do the hydra jobs through the flake's hydraJobs attr.

Which is what we should probably do anyway.

**Comment by jhbertra** [comment]
indeed, now that @shlevy added support for it

**Comment by shlevy** [comment]
> getting
> 
> ```
> $ nix-env -qaP -f ./release.nix
> error: cannot import '/nix/store/g5i4jgq6vl1z0w95g0npxzj7x4048rnr-source/nix/lib/purescript.nix', since path '/nix/store/wf4sdy9rjcvpnrwrsl8g7n1rjbby1b0a-source.drv' is not valid
> ```
> 
> issues when evaluating with darwin. Someone with intel darwin hardware will need to research that issue.

Isn't this issue just the need to add `--read-write-mode` to your `nix-env` invocation?

**Comment by jonringer** [comment]
`--read-write-mode` seems unholy

**Comment by jhbertra** [comment]
Closing stale PR

**Pull request closed without merging**
