### PR TITLE
Scp 4571 role tokens constraints work

### PR DESCRIPTION
**Pull request by dino-iog**
This is work for both SCP-4571 and SCP-4613, related to contracts with role tokens. Made a PR so we can share code as this is worked on.

### CODE REVIEW

**Comment by paluh** [comment]
Dino, can we check if we can hide back local functions in the validator code back (especially `step` but probably also `missingFromOutputValue`). Probably all the problems were related to to missing `INLINEABLE` and `OPTIONS_GHC` pragmas.
If it is too much work then please don't bother I can test it later on.

**Review by paluh — APPROVED** [review]

**Comment by dino-iog** [comment]
> Dino, can we check if we can hide back local functions in the validator code back (especially `step` but probably also `missingFromOutputValue`). Probably all the problems were related to to missing `INLINEABLE` and `OPTIONS_GHC` pragmas. If it is too much work then please don't bother I can test it later on.

@paluh If you need me to test anything or whatever we can pair some more. I can try things very quickly with my set up here.

**Review by bwbush — APPROVED** [review]
Looks good, but I decided to hold off retesting until the downstream bugs are fixed, too. Thanks!

**Comment by dino-iog** [comment]
Just did some rebasing and squashing to clean this up and brought it up-to-date with main. Now working on Jupyter notebook roles changes.

**Comment by dino-iog** [comment]
@paluh Also, I am working on undoing those aggressive inlinings we did as you suggested above.

**Pull request merged**
