### PR TITLE
SCP-3884 marlowe-cli/run-tests.sh should have better key handling

### PR DESCRIPTION
**Pull request by dino-iog**
I ran into problems with the `marlowe-cli/run-tests.sh` script when using wallet keys that also included staking, it was assuming no staking and generating an incorrect wallet address. It was suggested we modify the script to take explicit skey and address info instead of looking for the skey and vkey in hard-coded files in the `TREASURY` directory.

This ended up requiring some additional changes to how wallet keys are automatically created if they don't exist and some care to be taken in not clobbering a user's existing key files (which `cardano-cli` will cheerfully and silently do!)

Along the way I found some bugs and things that I went ahead and changed to work better or be clearer.

### CODE REVIEW

**Comment by paluh** [comment]
@dino-iog - could you please reopen this PR against sprint branch?

**Comment by paluh** [comment]
@dino-iog - could you please reopen this PR against sprint branch?

**Comment by dino-iog** [comment]
Oops! Will change to sprint branch shortly

**Comment by dino-iog** [comment]
PR made against the wrong branch (main), closing to recreate correctly.

**Pull request closed without merging**
