### PR TITLE
Folds and traversals for Extended Marlowe

### PR DESCRIPTION
**Pull request by paluh**
Just a proposition.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] [Test report is updated](https://github.com/input-output-hk/marlowe-cardano/blob/main/marlowe/test/test-report.md) (if relevant)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Comment by paluh** [comment]
@bwbush , @palas could you take a quick look at this small weekend project ;-) and tell me if I should proceed and write tests for that.
I'm also not sure if this should be part of the core `marlowe` lib - I wanted to use traversal to actually do the params substitution in the runtime.

**Review by bwbush — APPROVED** [review]
Nice design, and very useful.

I might refactor https://github.com/input-output-hk/marlowe-cardano/blob/b1b5d77e3fc78caa9fd67106e49c97ebc49438ec/marlowe-cli/src/Language/Marlowe/CLI/Analyze.hs#L794-L848 to use this new module instead of multiplate.

**Review by palas — APPROVED** [review]
It seems related to [this](https://github.com/input-output-hk/marlowe-cardano/blob/main/marlowe/src/Language/Marlowe/Util.hs#L76), but yours seems more flexible.
Looks good, but I think it could use a couple of extra comments and examples. In particular, the functions that say "topDown" and "bottomUp" and the `Visitor` datatype are a bit misterious to me

**Review by hrajchert — APPROVED** [review]
LGTM. I would add a simple test to show usage.

I don´t think it currently belongs to the plain `marlowe` repository as it doesn't have Extended Marlowe for the moment.

**Comment by bwbush** [comment]
Does this duplicate [the `multiplate` support](https://github.com/input-output-hk/marlowe-cardano/blob/911d7f66c24f3fa23c7f4e63eab87df7b5f81eeb/marlowe/src/Language/Marlowe/Core/V1/Plate.hs)? or is it complementary?

**Comment by paluh** [comment]
I'm not really familiar with `multiplate` approach. This implementation gives us ability to do top-down and bottom-up rewrites as well as folds. I'm in favor of `multiplate` if it gives us similar flexibility but is more standard in the Haskell ecosystem. We can shortly discuss this next week.

**Pull request closed without merging**
