### PR TITLE
Job query protocol

### PR DESCRIPTION
**Pull request by jhbertra**
Adds two new protocols to `marlowe-protocols`:

- `Job` protocol for issuing commands to start server jobs and asynchronously polling their statuses.
- `Query` protocol for querying resources from a server.

These protocols correspond to the command and query APIs of runtime components, respectively.

### CODE REVIEW

**Comment by bwbush** [comment]
@jhbertra, I'm unable to enter a development shell for this PR. Has the procedure changed, so the read-me is out of date?
```
$ git latest
387b93321e57acc55ff534ed12d1a024b1619fab (HEAD -> job-query-protocol, origin/job-query-protocol) Extract binaryProtocol helper

[bbush@oryx:/extra/iohk/marlowe-cardano.jqp/marlowe-chain-sync]$ nix develop .
trace: haskell-project-plan-to-nix-pkgs: To make project.plan-nix for haskell-project a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: haskell-project-plan-to-nix-pkgs: To materialize project.plan-nix for haskell-project entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: ERROR: cabal configure failed with:
Warning: The package list for 'hackage.haskell.org-at-2022-02-18T000000Z' is
19216 days old.
Run 'cabal update' to get the latest list of available packages.
Warning: Requested index-state 2022-02-18T00:00:00Z is newer than
'hackage.haskell.org-at-2022-02-18T000000Z'! Falling back to older state
(2022-02-17T23:17:49Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: marlowe-chain-sync-0.0.0.0 (user goal)
[__1] unknown package: typed-protocols (dependency of marlowe-chain-sync)
[__1] fail (backjumping, conflict set: marlowe-chain-sync, typed-protocols)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: marlowe-chain-sync, typed-protocols



error: attribute 'shellFor' missing

       at /nix/store/5c3r0m8x3z9d1lfw3lh8nx1lbvvna03b-source/overlays/haskell.nix:682:18:

          681|                   selectedCrossProjects;
          682|               in rawProject.hsPkgs.shellFor (args' // {
             |                  ^
          683|                   # Add inputs from the cross compilation shells
(use '--show-trace' to show detailed location information)
```

**Comment by bwbush** [comment]
Still failing:
```
[bbush@oryx:/extra/iohk/marlowe-cardano.jqp/marlowe-chain-sync]$ git pull
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 8 (delta 6), reused 8 (delta 6), pack-reused 0
Unpacking objects: 100% (8/8), 676 bytes | 169.00 KiB/s, done.
From github.com:input-output-hk/marlowe-cardano
   387b93321..0e5b6f1d9  job-query-protocol -> origin/job-query-protocol
Updating 387b93321..0e5b6f1d9
Fast-forward
 nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-protocols.nix | 7 +++++++
 1 file changed, 7 insertions(+)

[bbush@oryx:/extra/iohk/marlowe-cardano.jqp/marlowe-chain-sync]$ nix develop .
trace: haskell-project-plan-to-nix-pkgs: To make project.plan-nix for haskell-project a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: haskell-project-plan-to-nix-pkgs: To materialize project.plan-nix for haskell-project entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: ERROR: cabal configure failed with:
Warning: The package list for 'hackage.haskell.org-at-2022-02-18T000000Z' is
19216 days old.
Run 'cabal update' to get the latest list of available packages.
Warning: Requested index-state 2022-02-18T00:00:00Z is newer than
'hackage.haskell.org-at-2022-02-18T000000Z'! Falling back to older state
(2022-02-17T23:17:49Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: marlowe-chain-sync-0.0.0.0 (user goal)
[__1] unknown package: typed-protocols (dependency of marlowe-chain-sync)
[__1] fail (backjumping, conflict set: marlowe-chain-sync, typed-protocols)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: marlowe-chain-sync, typed-protocols



error: attribute 'shellFor' missing

       at /nix/store/5c3r0m8x3z9d1lfw3lh8nx1lbvvna03b-source/overlays/haskell.nix:682:18:

          681|                   selectedCrossProjects;
          682|               in rawProject.hsPkgs.shellFor (args' // {
             |                  ^
          683|                   # Add inputs from the cross compilation shells
(use '--show-trace' to show detailed location information)
```

**Review by bwbush — CHANGES_REQUESTED** [review]
The Haskell looks great, but I haven't been able to run the chainseekd because of the flake problem that I noted in another comment.

**Comment by jhbertra** [comment]
@bwbush sorry for not mentioning this - you don't need to use the project-specific nix flake anymore - use the root level shell.nix instead

**Review by bwbush — APPROVED** [review]
The `chainseekd` runs fine, when compiled in `nix-shell` instead of `nix develop .`.

I do think we should update the read-me for `chainsyncd`.

**Pull request merged**
