### PR TITLE
SCP-3216 Updated plutus-apps dependency to tip of its main

### PR DESCRIPTION
**Pull request by bwbush**
Summary:
1. Conforms to latest `plutus-apps` API and package names.
2. Revised Marlowe test cases because of min-ADA changes in `plutus-apps`.
3. Added executable for `psapigenerator` lost in `plutus-apps`.
4. Changes to PAB wallet configuration.
5. Workaround for broken `plutus-apps` purescript generation.
6. Upated servant purescript.
7. Workaround for invalid `.cabal` file in `plutus-apps`.
8. Updated obsolete plutus documentation in `doc/`.
9. Updated state index.
10. Clean lint.

Manually ran Marlowe test cases, and `nix-build` in root folder.

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Comment by bwbush** [comment]
@shlevy , the one test the `hydra-workaround` fails on is `nixpkgs-fmt`, but I don't get this error when I build on my NixOS laptop. The `hydra-workaround` reports
````console
building '/nix/store/7ydh1by67z9j5c9z3p9j45r7dp29bn7j-nixpkgs-fmt.drv'...
1 / 38 would have been reformatted
error: fail on changes
*** nixpkgs-fmt found files that haven't been formatted
*** Please run `nix-shell --run "nixpkgs-fmt ."` and commit the changes
error: builder for '/nix/store/7ydh1by67z9j5c9z3p9j45r7dp29bn7j-nixpkgs-fmt.drv' failed with exit code 1
````
but my local build succeeds and `nixpkgs-fmt` locally reports
```console
$ nix-shell --run "nixpkgs-fmt ."
0 / 37 have been reformatted
```
Thus it seems there is 38th `.nix` file that `hydra-workaround` doesn't like but which isn't present locally.

Please advise.

**Comment by bwbush** [comment]
@palas , both `nix-build` and `nix-build release.nix` succeed for 413017e1e040c59d2fcbbc10cc7be1c6f2509890 when run locally.

**Review by palas — APPROVED** [review]
It looks good to me

**Comment by palas** [comment]
I don't think `nix-build release.nix` does what CI does, but then again, the process we have died with "KILLED" so it looks like a lack of RAM problem to me 🤔

**Pull request merged**
